options:
  merge-default-rules: true
  formatter: stylish
  max-warnings: 100

files:
  include: 'src/scss/**/*.scss'

## Rules documentation: https://github.com/sasstools/sass-lint/tree/master/docs/rules
rules:
  declarations-before-nesting: 2
  empty-line-between-blocks: 2
  nesting-depth: 2
  no-css-comments: 2
  no-extends: 2
  no-ids: 2
  no-invalid-hex: 2
  no-misspelled-properties: 2
  no-transition-all: 2
  one-declaration-per-line: 2
  quotes: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  zero-unit: 2

  max-line-length:
    - 2
    -
      length: 120

  variable-for-property:
      - 2
      -
        properties:
        - border-color
        - background-color
        - color
        - font-size

  no-vendor-prefixes:
      - 2
      -
        ignore-non-standard: true

##  .block__element--modifier
  class-name-format:
    - 2
    -
      convention: hyphenatedbem

  no-duplicate-properties:
    - 2
    -
      exclude:
        - display
        - src

  indentation:
      - 2
      -
        size: 2

  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true

  no-warn: 1
  no-debug: 1

  mixins-before-declarations: 0
  force-element-nesting: 0
  leading-zero: 0
  force-pseudo-nesting: 0
  empty-args: 0
  no-important: 0
  hex-notation: 0
  property-sort-order: 0
  variable-name-format: 0
  clean-import-paths: 0
